'use strict';

// TODO (john@): IIFE should be generated by build, not brute-forced
(function (window, document, d3, jQuery, Promise) {
  var should = window.should = { };
  var speedCsvUrl = should.speedCsvUrl =
    '/DemoDataSeries.csv';
    //'//should-i-go.github.io/should-i-go-sandbox/DemoDataSeries.csv';

  jQuery(document).ready(function() {
    var speedCsvPromise = jQuery.when(jQuery.ajax(speedCsvUrl));

    speedCsvPromise.then(function loadCsv(content) {

      should.speedCsv = content;
      console.log('Loaded speed CSV data');

      return should.speedCsv;

    }).then(function parseCsv(speedCsv) {

      // shift strips the first (header row) off the raw, leaving only data
      var speedCsvRows = should.speedCsvRows = d3.csv.parse(speedCsv);
      console.log('Loaded speed CSV rows', speedCsvRows.length);

      return speedCsvRows;

    });


  });

})(window, document, d3, jQuery, Promise);